### ISSUE TITLE
Add alias for American spelling

### ISSUE THREAD

**Issue by 3noch** [strake/filtrable.hs#1]
The American spelling is, of course, "Filterable". It's a bit confusing to see different spelling variants in the same code base, so it seems like having the choice to use either would be best.

**Comment by strake** [comment]
I not follow your argument: adding an alias would **enable** spelling variants in the same code base.

If you want to call it "Filterable" in your code base, you can add a local alias `type Filterable = Filtrable`. I sympathize with disliking a library author's choice of name, but adding an alias would complicate the library and increase the barrier to readability between code using this class by its many names.

**Comment by 3noch** [comment]
Fair enough.

**Comment by oliver-batchelor** [comment]
May I suggest an alternative which is language agnostic? I also struggled to find this package because I looked for Filterable and we use British English in NZ, it's just not a common word...

Maybe something just like class Filter instead which can't be confused?

**Comment by strake** [comment]
> I also struggled to find this package

In that case i think an announcement on a mailing list would help, which i have now done to haskell-cafe. I'll insert the character sequence "filterable" into the cabal file too somehow if i can do so cleanly.

I would prefer to keep the name, as i have some code already using this class.
